include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    always_specify_types: false
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_await_in_return: true
    unnecessary_statements: true

analyzer:
  errors:
    invalid_annotation_target: ignore
